name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Post to a Slack channel
        # id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          # channel-id: 'CHANNEL_ID' # Slack channel id to post message
          slack-message: 'NISLAB HP „ÅÆ „Éì„É´„Éâ„Éª„Éá„Éó„É≠„Ç§ „ÇíÈñãÂßã„Åó„Åæ„Åó„ÅüÔºÅ'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn generate
        env:
          NUXT_ENV_CTF_ACCESS_TOKEN: ${{ secrets.NUXT_ENV_CTF_ACCESS_TOKEN }}
          NUXT_ENV_SPACE_ID: ${{ secrets.NUXT_ENV_SPACE_ID }}
      - run: tar -zcvf dist.tar.gz dist
      - run: echo "${{ secrets.SERVER_KEY }}" > aws_lightsail_key
      - run: chmod 600 ./aws_lightsail_key
      - run: scp -o StrictHostKeyChecking=no -i ./aws_lightsail_key ./dist.tar.gz ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/var/www/html
      - run: ssh -o StrictHostKeyChecking=no -i ./aws_lightsail_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd /var/www/html && rm -r dist && tar -zxvf dist.tar.gz && rm dist.tar.gz"
      - run: echo "üçè This job's status is ${{ job.status }}."
